### ISSUE TITLE
Style guide for R lectures and courses

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#1]
See here for initial issue: https://github.com/UofTCoders/council/issues/175

### Initial comments:
Originally from pull request https://github.com/UofTCoders/council/pull/164

@lwjohnst86 :
For the file naming, it might be best to encourage them to follow a standard that has been developed, rather than create their own. Like Google's R style guide https://google.github.io/styleguide/Rguide.xml

@joelostblom :
I agree that the students should follow an already developed style guideline, and I think it is important that we are consistent across the lectures as well.

I think it is trickier to agree on which style to follow, since R does not have official guidelines. I believe Google's recommendations appear to be sound in large, with the exception of using periods in object/variable and column names. This is confusion for me coming from and object oriented language and I would prefer snake case (a.k.a. underscores: variable_name) in variable names and Pascal / upper camel case in column names (ColumnName). But, and I keep saying this, I'm happy to conform to other standards based on advice from the more experienced R-users among us and discussion with the rest of the group.

However, I do believe underscores would be helpful for students if they are ever to read or write code written in another language, where periods have special meaning. This coding style is not without precedence in the R community, e.g. Hadley Wickham's stat 405 course recommends underscores for variable names, as does this R style guide. The most compelling reason to use underscores in our case might be to stay consistent with the recommendations in the tidyverse guidelines (naturally similar to those from stat 405), since we will largely be using packages from the tidyverse and it would be confusing to mix these conventions with those from another style guide. The tidyverse favors underscores for objects, functions, and parameters, e.g. tbl_df, group_by, geom_point, facet_wrap, etc. The tidyverse style guide is the most exhaustive of the ones I have seen, and often includes justifications of the chosen style, which helps understanding and memorization. There is also a package, lintr, for automatically controlling for adherence to the tidyverse guidelines, and I believe this is the syntax checker that is builtin to Rstudio.

Some additional info: Bioconductor recommends lower camel case. Some Swedish research shows that all three styles are common in existing CRAN packages. This is a helpful SO question, with several good answers.

**Comment by lwjohnst86** [comment]
@joelostblom I 100% agree with you regarding the periods. `snake_case` for functions/objects and CamelCase for variables is what I use and recommend. Others such as Hadley also use this style. Let's stick with that. Maybe we create our own reference for the students, based on the Google style guide but slightly modified?

**Comment by lwjohnst86** [comment]
Actually, Hadley has already set up a page for the style: http://adv-r.had.co.nz/Style.html

**Comment by joelostblom** [comment]
Yes, that one looks like a briefer version [of the content I linked previously](http://style.tidyverse.org/index.html), isn't it?

According to those guidelines, `snake_case` is used pretty much everywhere, including variable names:

> Variable and function names should use only lowercase letters, numbers, and `_`.

I didn't find anything for column names in the tidyverse style guide, but in the examples, [such as for mutate](http://dplyr.tidyverse.org/reference/mutate.html), `snake_case` is used.

**Comment by lwjohnst86** [comment]
Aaah, of course there is an entire book format website on this... again through the tidyverse.. see here: http://style.tidyverse.org/index.html

**Comment by lwjohnst86** [comment]
It doesn't include column variable naming though... I think that might have to do with the fact that for many datasets, the column names are already set up and it would be a hassle to rename alllll of them (if it's a big dataset).

We could make a reference to it in the lectures and say try to use CamelCase for data variable names.

**Comment by joelostblom** [comment]
Haha yes @lwjohnst86, you essentially posted what I said [in my comment above](https://github.com/UofTCoders/rcourse/issues/1#issuecomment-315625882)! =) `snake_case` is used for column names in the tidyverse documentation.

**Comment by lwjohnst86** [comment]
Ohh, jeez, wow, sorry, I kept looking at the wrong website when you linked that style guide.... drrrrrrrrrrrup... haha oops, sorry bout that.

As for snake case with column names... I don't like that at all... A brief google search seems to show that naming conventions for database column names are pretty varied... I'd say use CamelCase for data variables, to separate it from functions and object variable names. Thoughts?

**Comment by lwjohnst86** [comment]
@joelostblom I just wanted to imitate you that's all... You know what they say about imitation right? "Imitation is the sincerest/highest form of flattery" :stuck_out_tongue_winking_eye:

**Comment by joelostblom** [comment]
Haha, I thought they said that stealing was the highest form of flattery... gotta check my wallet before I leave the next coders meeting!

I largely agree regarding column names. I actually switched from underscores to using upper CamelCase myself with column names in pandas and seaborn, although many of the example data sets there use underscores. My main reason for this is that it looks better when displaying the data as a table, and also as the default axis labels when plotting (although I would change any axis labels from "PascalCase" to "Pascal case" before publishing anyways...). 

However, I have recently started looking a bit at SQL, where there seems to be good reasons to prefer lowercase with underscores. Mostly because variable names are case insensitive unless quoted, and I would not want to keep quoting column names for no good reason. I also read something on that with Windows there might be additional problems, because some SQL implementation (I think MySQL) converts column names to lower case by default, so any case variation would be lost (not sure about source credibility).

Looking at examples from the documentation of major packages and programs that I have used at least somewhat briefly, all of them use `snake_case` for column names. These include

- pandas
- seaborn
- tidyverse
- data.table
- PostgreSQL
- MySQL

So, although most of them don't make stylistic recommendations, not a single one uses any form of camel case... Hmmmm... I might just have convinced myself to switch back to underscores...

What do you think? Which are your reasons for using PascalCase? I think of you as a die hard dplyr/Hadley fan, so I am curious to why you are not following his conventions here =) Is it from some old lingering SASS convention? 😱 

What I do know for sure is that I prefer column names to be singular and not contain whitespaces.

**Comment by linamnt** [comment]
Okay so maybe for the assignment,once we decide, we should say to include a blurb about the style we're going to expect students to use?

**Comment by lwjohnst86** [comment]
Hmm, regarding PascalCase vs snake_case... @joelostblom Your arguments convince me as well... Plus I just read [this blog](https://whathecode.wordpress.com/2011/02/10/camelcase-vs-underscores-scientific-showdown/) that says camel/pascal case is slower to read... OK, snake case it is.. Unless there are strong arguments against.
