### ISSUE TITLE
Aim for publication to figshare for the final project?

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/rcourse#104]
At least as an option?

https://figshare.com/about
They handle a bunch of things, including posters and figures, so we could publish result on an existing data set there I believe. Thoughts? Anyone with experience publishing there?

**Comment by joelostblom** [comment]
Including a github repo, so potentially students could upload their entire workflow https://mozillascience.github.io/code-research-object/

**Comment by lwjohnst86** [comment]
Yes, I use figshare for everything from my entire project folder (code and suppl analyses only), posters, and slides. This was actually one of the places I was thinking of using for the project, since bioArxiv/arXiv are more for 'novel' scientific contributions. Depending on the project, they could go to the arxivs

**Comment by lwjohnst86** [comment]
My figshare profile https://figshare.com/authors/Luke_Johnston/796270

**Comment by lwjohnst86** [comment]
Yes, we'll do that for them I think. Or if they want to. It might be easier if we do it. Thoughts?

**Comment by joelostblom** [comment]
Maybe we can offer them the option to help them do it for those groups that
are interested?
