### ISSUE TITLE
Tidy up and reformat lessons so they are all consistent

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#141]
Just so when we finish the course, everything is cleaned and consistent and tidy.

**Comment by lwjohnst86** [comment]
(more note to myself) 

Move images into ~`_images`~ `images/` and data into ~`_data`~ `data/`

**Comment by joelostblom** [comment]
What's the benefit of the leading underscore? Is it indicating that these files are resources used by another document rather than being used directly or something like that? I know jekyll does it also, so I'm just trying to understand if there are any advantages to this over just having `img` and `data`, which is what I do (or maybe `res/img` and `res/data`, res = 'resources).

**Comment by lwjohnst86** [comment]
I initially wrote the `_` because in `rmarkdown::render_site()` any folder or file that begins with `.` or `_` is not included in the site generation, so you can store style files, etc in them. However, we actually want the images and data in the site. After I wrote that comment, I realized that it should actually be *without* an underscore.

**Comment by lwjohnst86** [comment]
Done tidying images #146 and data #147 

Just need to unhide all challenges and format them the same. Some challenges are in blockquotes while others are not.
