### ISSUE TITLE
Licensing for student repos

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#151]
Thoughts on licensing? I've already put a MIT and CC-BY 4.0 README shields in the repos.

**Comment by joelostblom** [comment]
Initially, I though anything that allows sharing with contribution would be appropriate. Since it is the first time for many of the students putting work online, they might not feel comfortable if someone just "takes" it. But on second though, I think we should get them used to this right away and emphasize that it is not dangerous, so MIT sounds good to me. What's the advantage to include both?

**Comment by QuLogic** [comment]
MIT is for code; it's not really applicable to documentation. Just like the equivalent for GPL would be GFDL. Though if it were just a short readme, it's probably not a big deal.

**Comment by joelostblom** [comment]
I see, thanks! Then it sounds like we are good with the licenses Luke added.
