### ISSUE TITLE
Where will final assignments be created?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/rcourse#41]
Assuming they should be under version control and on GitHub... Do we create a repo on UofTCoders for each project and add the team members to each their respective repo? Do we have one of the members create a repo and the other share? If so, how do we decide which student gets the original repo (thus full control and potential perception that it is the lead repo..)?

My thought:

- We create each repo on the UofTCoders. 
- Add each member as a contributor. 
- Set the master branch as protected (so no one can push to it). 
- Each member forks it.
- Each member submits PR to the main one to keep it updated.
- Any can merge PRs.

This way, we know whose done what, we can help out more closely, we can intervene if necessary (aka, resolve any file conflicts), and easily provide direct feedback on the project.

Others opinions?

**Comment by joelostblom** [comment]
The only issue I can think of is that there will be many repositories under UofTCoders, especially if the course is taught for several years. It would also be nice to sort projects by when they were created. Potentially create a folder under the rcourse repository and subfolders for each teaching semester? Can we set permissions so that they can only push commit to that one folder? Or create one new repository under UofTCoders, rcourse-student-projects, and a subfolders for each teaching semester?

**Comment by lwjohnst86** [comment]
Hmm, as far as I am aware, there is no way to set permissions on only some folders/subfolders. Plus I'd prefer if the rcourse repo were focused on the specific aim of hosting the website.

The benefit of having each project be its own repo (with the term/year in the name to order them) would be that team members only get notifications of their own project, its self-contained and specific, and the others can't easily try to change or edit other teams projects.

But I do agree with you that there will start to be a lot of repos, which might be not cool. Though, we could always archive them to keep them out of view (if that's what archive does...)

**Comment by joelostblom** [comment]
Meeting conclusions: One repo per student group under the UofT coders organization. We are owners.
